services:
  webapigetway:
    image: ${DOCKER_REGISTRY-}webapigetway
    build:
      context: .
      dockerfile: WebApiGetway/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - UserApiServiceUrl=http://userapiservice
    depends_on:
      - userapiservice
      # - rentobjectapiservice
      - offerapiservice
      - orderapiservice
      # - locationapiservice
      # - reviewapiservice
      - rabbitmq
      - translationapiservice


  locationapiservice:
    build:
      context: .
      dockerfile: LocationApiService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection string for Postgres service (adjust values in code if needed)
      #- ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
      - rabbitmq


  userapiservice:
    build:
      context: .
      dockerfile: UserApiService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection string for Postgres service (adjust values in code if needed)
      #- ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
      - rabbitmq
      - locationapiservice


  offerapiservice:
    build:
      context: .
      dockerfile: OfferApiService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection string for Postgres service (adjust values in code if needed)
      #- ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
      - rabbitmq
      - locationapiservice



  orderapiservice:
    build:
      context: .
      dockerfile: OrderApiService/Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection string for Postgres service (adjust values in code if needed)
      #- ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
      - rabbitmq
      - locationapiservice



  reviewapiservice:
    build:
      context: .
      dockerfile: ReviewApiService/Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection string for Postgres service (adjust values in code if needed)
      #- ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
      - rabbitmq
      - locationapiservice




  translationapiservice:
    build:
      context: .
      dockerfile: TranslationApiService/Dockerfile
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection string for Postgres service (adjust values in code if needed)
      #- ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
      - rabbitmq
      - locationapiservice


  attractionapiservice:
    build:
      context: .
      dockerfile: AttractionApiService/Dockerfile
    ports:
      - "5007:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection string for Postgres service (adjust values in code if needed)
      #- ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
      - rabbitmq
      - locationapiservice


  statisticapiservice:
    build:
      context: .
      dockerfile: StatisticApiService/Dockerfile
    ports:
      - "5008:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Connection string for Postgres service (adjust values in code if needed)
      #- ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgrespw
    depends_on:
      - postgres
      - rabbitmq
      - locationapiservice

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      #- POSTGRES_DB=userdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  # frontend:
  #   build:
  #     context: ../../front
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - webapigetway


volumes:
  pgdata:
  pgadmin-data: